version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"

    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
      timezone: "Etc/UTC"

    groups:
      all-npm-dependencies:
        patterns:
          - "*"

    commit-message:
      prefix: "chore(deps)"
